on: [push]

jobs:
  build-and-test:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build
